# Generated by Django 3.0.6 on 2020-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'flower',
            },
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'leaf',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=50)),
                ('flowerchars', models.ManyToManyField(related_name='flower', to='front.Flower')),
                ('leafchars', models.ManyToManyField(related_name='leaf', to='front.Leaf')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
